### PR TITLE
install jlink tools

### PR DESCRIPTION
**Pull request by thebhef**
Install jlink tools to support launching jlink GDB from inside the container

### CODE REVIEW

**Comment by thebhef** [comment]
Current dependencies on/for this PR:
* main
  * **PR #21** <a href="https://app.graphite.dev/github/pr/StaflSystems/stafl-devcontainer/21" target="_blank">Graphite</a> 
    * **PR #22** <a href="https://app.graphite.dev/github/pr/StaflSystems/stafl-devcontainer/22" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/StaflSystems/stafl-devcontainer/22?utm_source=stack-comment).

**Review by mns4595 — APPROVED** [review]

**Comment by thebhef** [comment]
@thebhef started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/StaflSystems/stafl-devcontainer/22).

**Comment by thebhef** [comment]
[Graphite](https://app.graphite.dev/github/pr/StaflSystems/stafl-devcontainer/22) rebased this pull request as part of a merge.

**Comment by thebhef** [comment]
@thebhef merged this pull request with [Graphite](https://app.graphite.dev/github/pr/StaflSystems/stafl-devcontainer/22).

**Pull request merged**
